# These are supported funding model platforms

github: cerebrux
ko_fi: cerebrux
custom: ["https://donate.utappia.org", "https://www.paypal.com/donate/?hosted_button_id=SATQ6Y9S3UCSG"]
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
